import { EVERY_DAY, WEEKDAYS } from "./weekday-selection.ts";

export type OfficialTaskCategory="self_care"|"learning"|"exercise"|"character"|"housework"|"social"|"health"|"other";
export type OfficialTaskTimeSlot="wake_up"|"before_breakfast"|"before_school"|"after_school"|"after_dinner"|"before_bed"|"anytime";
export type OfficialTaskAgeGroup="age_3_5"|"age_6_8"|"age_9_12"|"age_13_plus"|"all";

export type OfficialTask={
  id:string;title:string;icon:string;category:OfficialTaskCategory;suggestedStars:number;ageGroups:OfficialTaskAgeGroup[];
  timeSlot:OfficialTaskTimeSlot;difficulty:1|2|3|4|5;popularityScore:number;isRecommended:boolean;enabled:boolean;
  keywords:string[];createdAt:string;sortOrder:number;description?:string;suggestedWeekdays?:number[];tags?:string[];
};

export type OfficialTaskTemplate={id:string;title:string;description:string;icon:string;ageGroups:OfficialTaskAgeGroup[];taskIds:string[];recommended:boolean;sortOrder:number};

export const CATEGORY_META:Record<OfficialTaskCategory,{label:string;icon:string}>={
  self_care:{label:"生活自理",icon:"🪥"},learning:{label:"學習",icon:"📚"},exercise:{label:"運動",icon:"⚽"},character:{label:"品格",icon:"❤️"},
  housework:{label:"家事",icon:"🏠"},social:{label:"社交",icon:"🤝"},health:{label:"健康",icon:"🍎"},other:{label:"其他",icon:"🎯"},
};
export const TIME_SLOT_META:Record<OfficialTaskTimeSlot,{label:string;icon:string;order:number}>={
  wake_up:{label:"起床",icon:"🌞",order:0},before_breakfast:{label:"早餐前",icon:"🍳",order:1},before_school:{label:"上學前",icon:"🎒",order:2},
  after_school:{label:"放學後",icon:"🏫",order:3},after_dinner:{label:"晚餐後",icon:"🍽️",order:4},before_bed:{label:"睡前",icon:"🌙",order:5},anytime:{label:"全天皆可",icon:"⭐",order:6},
};
export const AGE_GROUP_META:Record<OfficialTaskAgeGroup,string>={age_3_5:"3～5 歲",age_6_8:"6～8 歲",age_9_12:"9～12 歲",age_13_plus:"13 歲以上",all:"不限"};
export const ALL_WEEKDAYS=[...EVERY_DAY];
export const SCHOOL_WEEKDAYS=[...WEEKDAYS];
const ALL_AGES:OfficialTaskAgeGroup[]=["age_3_5","age_6_8","age_9_12","age_13_plus"];
const SCHOOL_AGES:OfficialTaskAgeGroup[]=["age_6_8","age_9_12","age_13_plus"];
type Seed=[string,string,string,OfficialTaskCategory,OfficialTaskTimeSlot,number,1|2|3|4|5,OfficialTaskAgeGroup[]?,boolean?,number[]?];
const seeds:Seed[]=[
  ["wake-fold-blanket","起床自己摺棉被","🛏️","self_care","wake_up",1,2,ALL_AGES,true],["wake-toilet","起床後上廁所","🚽","self_care","wake_up",1,1,ALL_AGES],["wake-wash-face","起床後洗臉","🧼","self_care","wake_up",1,1,ALL_AGES,true],["morning-brush-teeth","早上刷牙","🪥","health","wake_up",1,1,ALL_AGES,true],["dress-yourself","自己換衣服","👕","self_care","wake_up",1,2,ALL_AGES,true],["comb-hair","梳頭髮","🪮","self_care","wake_up",1,1,ALL_AGES],["open-curtains","起床拉開窗簾","🌤️","housework","wake_up",1,1,ALL_AGES],["morning-water","起床喝一杯水","💧","health","wake_up",1,1,ALL_AGES,true],
  ["eat-breakfast","吃早餐","🍞","health","before_breakfast",1,1,ALL_AGES,true],["breakfast-on-time","早餐不拖延","⏰","character","before_breakfast",1,2,ALL_AGES],["wash-hands-before-meal","飯前洗手","🫧","health","before_breakfast",1,1,ALL_AGES,true],["help-set-table","幫忙拿餐具","🥢","housework","before_breakfast",1,1,ALL_AGES],["breakfast-clear-dishes","早餐後收餐具","🍽️","housework","before_school",1,2,ALL_AGES],["prepare-bottle","準備水壺","🫗","self_care","before_school",1,1,SCHOOL_AGES],["check-contact-book","檢查聯絡簿","📒","learning","before_school",1,2,SCHOOL_AGES,true],["check-schoolbag","檢查書包","🎒","learning","before_school",1,2,SCHOOL_AGES,true],["leave-on-time","準時出門","🚪","character","before_school",2,2,SCHOOL_AGES,true],["wear-mask-needed","需要時戴好口罩","😷","health","before_school",1,1,ALL_AGES],
  ["shoes-in-place","鞋子放定位","👟","self_care","after_school",1,1,ALL_AGES,true],["bag-in-place","書包放定位","🎒","self_care","after_school",1,1,SCHOOL_AGES,true],["wash-water-bottle","水壺拿出來清洗","🫗","housework","after_school",1,2,SCHOOL_AGES],["take-contact-book","拿出聯絡簿","📒","learning","after_school",1,1,SCHOOL_AGES],["finish-homework","完成功課","✏️","learning","after_school",2,3,SCHOOL_AGES,true],["check-homework","檢查功課","✅","learning","after_school",1,3,SCHOOL_AGES,true],["organize-schoolbag","整理書包","🎒","learning","after_school",2,2,SCHOOL_AGES,true],["prepare-tomorrow","準備隔天用品","📦","self_care","after_school",1,2,SCHOOL_AGES],["read-10","閱讀 10 分鐘","📖","learning","after_school",1,1,ALL_AGES,true],["read-20","閱讀 20 分鐘","📚","learning","after_school",2,2,SCHOOL_AGES,true],["english-10","英文練習 10 分鐘","🔤","learning","after_school",1,2,SCHOOL_AGES],["vocabulary","背單字","📝","learning","after_school",2,3,SCHOOL_AGES],["handwriting","練字","✍️","learning","after_school",1,2,SCHOOL_AGES],["math-practice","數學練習","➗","learning","after_school",2,3,SCHOOL_AGES],["preview-lessons","預習","🔎","learning","after_school",2,3,SCHOOL_AGES],["review-lessons","複習","🧠","learning","after_school",2,3,SCHOOL_AGES],
  ["swim-training","游泳訓練","🏊","exercise","after_school",2,3,SCHOOL_AGES,true,[1,2,3,4,5,6]],["jump-rope-100","跳繩 100 下","🪢","exercise","after_school",1,2,SCHOOL_AGES,true],["jump-rope-300","跳繩 300 下","🪢","exercise","after_school",2,3,["age_9_12","age_13_plus"]],["run-10","跑步 10 分鐘","🏃","exercise","after_school",2,2,SCHOOL_AGES],["outdoor-30","戶外活動 30 分鐘","🌳","exercise","after_school",2,2,ALL_AGES,true],["ride-bike","騎腳踏車","🚲","exercise","after_school",2,2,ALL_AGES],["stretch-10","拉筋 10 分鐘","🤸","exercise","after_school",1,2,SCHOOL_AGES],["ball-sports","球類運動","⚽","exercise","after_school",2,3,SCHOOL_AGES],["core-exercise","核心運動","💪","exercise","after_school",2,4,["age_9_12","age_13_plus"]],["organize-sports-gear","運動後整理用品","🎽","self_care","after_school",1,2,SCHOOL_AGES],
  ["dinner-clear-dishes","吃完飯收餐具","🍽️","housework","after_dinner",1,2,ALL_AGES,true],["load-dishwasher","把餐具放進洗碗機","🧺","housework","after_dinner",2,2,SCHOOL_AGES],["wipe-table","擦桌子","🧽","housework","after_dinner",1,2,ALL_AGES],["put-away-toys","收玩具","🧸","housework","after_dinner",1,2,ALL_AGES,true],["tidy-room","整理房間","🛏️","housework","after_dinner",2,3,SCHOOL_AGES,true],["tidy-desk","整理書桌","🪑","housework","after_dinner",2,2,SCHOOL_AGES],["fold-clothes","摺衣服","👕","housework","after_dinner",2,3,SCHOOL_AGES],["put-away-clothes","收衣服","🧺","housework","after_dinner",1,2,SCHOOL_AGES],["take-trash","倒垃圾","🗑️","housework","after_dinner",2,2,SCHOOL_AGES],["water-plants","澆花","🪴","housework","after_dinner",1,1,ALL_AGES],["sweep-floor","掃地","🧹","housework","after_dinner",2,3,SCHOOL_AGES],["vacuum-floor","吸地板","🧹","housework","after_dinner",2,3,SCHOOL_AGES],["mop-floor","擦地板","🧼","housework","after_dinner",3,4,["age_9_12","age_13_plus"]],["organize-shoes","整理鞋子","👞","housework","after_dinner",1,2,ALL_AGES],["refill-tissue","補充衛生紙","🧻","housework","after_dinner",1,1,SCHOOL_AGES],
  ["shower-yourself","自己洗澡","🛁","self_care","before_bed",2,2,ALL_AGES,true],["dry-after-shower","洗澡後擦乾身體","🧴","self_care","before_bed",1,1,ALL_AGES],["change-pajamas","換睡衣","🌙","self_care","before_bed",1,1,ALL_AGES],["sort-dirty-clothes","整理髒衣服","🧺","self_care","before_bed",1,2,ALL_AGES],["bedtime-brush-teeth","睡前刷牙","🪥","health","before_bed",1,1,ALL_AGES,true],["use-floss","使用牙線","🦷","health","before_bed",1,2,SCHOOL_AGES,true],["tomorrow-clothes","整理明天衣物","👔","self_care","before_bed",1,2,SCHOOL_AGES],["tomorrow-schoolbag","整理明天書包","🎒","learning","before_bed",2,2,SCHOOL_AGES,true],["bedtime-story","閱讀睡前故事","📖","learning","before_bed",1,1,ALL_AGES,true],["toilet-before-bed","睡前上廁所","🚽","self_care","before_bed",1,1,ALL_AGES],["bed-on-time","準時上床","🛏️","health","before_bed",2,2,ALL_AGES,true],["sleep-before-9","9 點前睡覺","9️⃣","health","before_bed",2,2,["age_3_5","age_6_8"]],["sleep-before-930","9 點半前睡覺","🌙","health","before_bed",2,2,["age_6_8","age_9_12"]],["sleep-before-10","10 點前睡覺","🔟","health","before_bed",2,2,["age_9_12","age_13_plus"]],
  ["say-thanks","主動說謝謝","🙏","character","anytime",1,1,ALL_AGES,true],["apologize","做錯事情主動道歉","🙇","character","anytime",2,2,ALL_AGES,true],["share-toys","分享玩具","🧸","social","anytime",1,2,["age_3_5","age_6_8"]],["help-siblings","幫助兄弟姊妹","🤝","social","anytime",2,2,ALL_AGES],["help-family","幫助家人","💗","character","anytime",2,2,ALL_AGES,true],["care-family","主動關心家人","🥰","social","anytime",1,2,ALL_AGES],["express-emotions","好好表達情緒","💬","character","anytime",2,3,ALL_AGES,true],["calm-when-angry","生氣時先冷靜","🧘","character","anytime",2,3,ALL_AGES,true],["do-not-interrupt","不插嘴","🤫","social","anytime",1,2,ALL_AGES],["speak-politely","說話有禮貌","😊","social","anytime",1,2,ALL_AGES,true],["wait-in-line","排隊等待","🚶","social","anytime",1,2,ALL_AGES],["keep-promise","遵守約定","🤞","character","anytime",2,3,SCHOOL_AGES],["put-own-things-away","主動收拾自己的東西","📦","character","anytime",2,2,ALL_AGES,true],["finish-without-complaint","完成事情不抱怨","💪","character","anytime",2,3,SCHOOL_AGES],["compliment-someone","今天稱讚別人一句","🌷","social","anytime",1,2,ALL_AGES],["one-kind-act","今天做一件善良的事","💝","character","anytime",2,2,ALL_AGES,true],
  ["happy-journal","寫下一件今天開心的事","🌈","other","anytime",1,1,SCHOOL_AGES,true],["tomorrow-small-goal","設定明天的一個小目標","🎯","other","before_bed",1,2,SCHOOL_AGES],
  ["drink-water","喝足夠的水","💧","health","anytime",1,2,ALL_AGES,true],["eat-fruit","吃一份水果","🍎","health","anytime",1,1,ALL_AGES,true],["eat-vegetables","吃一份蔬菜","🥦","health","anytime",1,2,ALL_AGES,true],["avoid-sugary-drinks","少喝含糖飲料","🥤","health","anytime",2,2,SCHOOL_AGES],["sunshine","戶外曬太陽","☀️","health","anytime",1,1,ALL_AGES],["good-posture","保持正確坐姿","🪑","health","anytime",1,2,SCHOOL_AGES],["eye-rest","用眼 30 分鐘休息","👀","health","anytime",1,2,SCHOOL_AGES,true],["cover-cough","咳嗽時遮住口鼻","🤧","health","anytime",1,1,ALL_AGES],["wash-hands-home","回家先洗手","🫧","health","after_school",1,1,ALL_AGES,true],
];

export const OFFICIAL_TASKS:OfficialTask[]=seeds.map(([id,title,icon,category,timeSlot,suggestedStars,difficulty,ageGroups=ALL_AGES,isRecommended=false,suggestedWeekdays],index)=>({
  id:`official-${id}`,title,icon,category,timeSlot,suggestedStars,difficulty,ageGroups,popularityScore:Math.max(35,100-(index*7)%61),isRecommended,enabled:true,
  keywords:[title,CATEGORY_META[category].label,TIME_SLOT_META[timeSlot].label,title.replace(/\s+/g,"")],tags:[CATEGORY_META[category].label,TIME_SLOT_META[timeSlot].label],
  description:`培養「${title}」的日常好習慣。`,suggestedWeekdays:suggestedWeekdays||((timeSlot==="before_school"||category==="learning")?SCHOOL_WEEKDAYS:ALL_WEEKDAYS),
  createdAt:`2026-07-${String(1+index%15).padStart(2,"0")}T00:00:00.000Z`,sortOrder:index,
}));

const taskIds=(...ids:string[])=>ids.map(id=>`official-${id}`);
export const OFFICIAL_TASK_TEMPLATES:OfficialTaskTemplate[]=[
  {id:"pack-toddler-routine",title:"幼兒生活養成包",description:"從起床、收玩具到睡前，建立基本生活自理。",icon:"👶",ageGroups:["age_3_5"],taskIds:taskIds("wake-wash-face","morning-brush-teeth","dress-yourself","put-away-toys","shower-yourself","bedtime-brush-teeth","bed-on-time"),recommended:true,sortOrder:0},
  {id:"pack-lower-primary",title:"國小低年級包",description:"上學準備、功課與規律作息一次建立。",icon:"🎒",ageGroups:["age_6_8"],taskIds:taskIds("check-contact-book","check-schoolbag","finish-homework","read-10","organize-schoolbag","bedtime-brush-teeth"),recommended:true,sortOrder:1},
  {id:"pack-upper-primary",title:"國小高年級包",description:"強化自主學習、整理與時間管理。",icon:"📖",ageGroups:["age_9_12"],taskIds:taskIds("check-homework","review-lessons","read-20","tomorrow-schoolbag","good-posture","eye-rest"),recommended:true,sortOrder:2},
  {id:"pack-swimmer",title:"游泳孩子包",description:"游泳日的訓練、伸展與用品整理。",icon:"🏊",ageGroups:SCHOOL_AGES,taskIds:taskIds("swim-training","stretch-10","organize-sports-gear","drink-water","bed-on-time"),recommended:false,sortOrder:3},
  {id:"pack-reading",title:"閱讀養成包",description:"從短時間閱讀逐步建立穩定閱讀習慣。",icon:"📚",ageGroups:ALL_AGES,taskIds:taskIds("read-10","read-20","bedtime-story","eye-rest"),recommended:true,sortOrder:4},
  {id:"pack-housework",title:"家事高手包",description:"從簡單收拾到主動分擔家庭工作。",icon:"🧹",ageGroups:SCHOOL_AGES,taskIds:taskIds("dinner-clear-dishes","wipe-table","tidy-room","fold-clothes","sweep-floor","take-trash"),recommended:false,sortOrder:5},
  {id:"pack-character",title:"品格教育包",description:"練習感謝、道歉、同理與遵守約定。",icon:"😊",ageGroups:ALL_AGES,taskIds:taskIds("say-thanks","apologize","express-emotions","keep-promise","one-kind-act"),recommended:true,sortOrder:6},
  {id:"pack-sleep",title:"作息養成包",description:"把洗澡、整理、刷牙與準時上床串成固定流程。",icon:"😴",ageGroups:ALL_AGES,taskIds:taskIds("shower-yourself","change-pajamas","tomorrow-clothes","bedtime-brush-teeth","toilet-before-bed","bed-on-time"),recommended:true,sortOrder:7},
];

export const officialTaskSearchText=(task:OfficialTask)=>[task.title,CATEGORY_META[task.category].label,TIME_SLOT_META[task.timeSlot].label,task.icon,task.description,...task.keywords,...(task.tags||[])].join(" ").normalize("NFKC").toLocaleLowerCase("zh-TW");
export const officialAgeLabel=(groups:OfficialTaskAgeGroup[])=>groups.includes("all")?"不限":groups.map(group=>AGE_GROUP_META[group]).join("、");
