param(
  [string]$LogoPath = ""
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent $PSScriptRoot
$public = Join-Path $root "public"
if (-not $LogoPath) { $LogoPath = Join-Path $public "star-diary-logo.jpg" }
$source = [System.Drawing.Image]::FromFile($LogoPath)
$primary = [System.Drawing.ColorTranslator]::FromHtml("#2563A6")
$white = [System.Drawing.Color]::White

function New-SquarePng([string]$name, [int]$size, [bool]$maskable = $false) {
  $bitmap = [System.Drawing.Bitmap]::new($size, $size, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
  try {
    $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
    $graphics.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
    if ($maskable) {
      $graphics.Clear($white)
      $inner = [int][Math]::Round($size * 0.80)
      $offset = [int](($size - $inner) / 2)
      $graphics.DrawImage($source, $offset, $offset, $inner, $inner)
    } else {
      $graphics.Clear($white)
      $graphics.DrawImage($source, 0, 0, $size, $size)
    }
    $bitmap.Save((Join-Path $public $name), [System.Drawing.Imaging.ImageFormat]::Png)
  } finally {
    $graphics.Dispose()
    $bitmap.Dispose()
  }
}

function New-SplashPng([int]$width, [int]$height) {
  $bitmap = [System.Drawing.Bitmap]::new($width, $height, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
  try {
    $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
    $graphics.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
    $graphics.Clear($primary)

    # Match the icon-only launch surface generated by installed iOS PWAs.
    $logoSize = [int][Math]::Round([Math]::Min($width * 0.32, $height * 0.18))
    $left = [int](($width - $logoSize) / 2)
    $top = [int](($height - $logoSize) / 2)
    $diameter = [int][Math]::Round($logoSize * 0.36)
    $path = [System.Drawing.Drawing2D.GraphicsPath]::new()
    $path.AddArc($left, $top, $diameter, $diameter, 180, 90)
    $path.AddArc($left + $logoSize - $diameter, $top, $diameter, $diameter, 270, 90)
    $path.AddArc($left + $logoSize - $diameter, $top + $logoSize - $diameter, $diameter, $diameter, 0, 90)
    $path.AddArc($left, $top + $logoSize - $diameter, $diameter, $diameter, 90, 90)
    $path.CloseFigure()
    $graphics.SetClip($path)
    $graphics.DrawImage($source, $left, $top, $logoSize, $logoSize)
    $graphics.ResetClip()
    $path.Dispose()
    $bitmap.Save((Join-Path $public "splash-${width}x${height}.png"), [System.Drawing.Imaging.ImageFormat]::Png)
    $bitmap.Save((Join-Path $public "launch-v2-${width}x${height}.png"), [System.Drawing.Imaging.ImageFormat]::Png)
  } finally {
    $graphics.Dispose()
    $bitmap.Dispose()
  }
}

try {
  foreach ($size in @(72, 96, 128, 144, 152, 192, 384, 512)) { New-SquarePng "icon-$size.png" $size }
  New-SquarePng "icon-maskable-192.png" 192 $true
  New-SquarePng "icon-maskable-512.png" 512 $true
  New-SquarePng "android-chrome-192.png" 192
  New-SquarePng "android-chrome-512.png" 512
  New-SquarePng "apple-touch-icon.png" 180
  New-SquarePng "favicon-16.png" 16
  New-SquarePng "favicon-32.png" 32

  foreach ($splash in @(@(640,1136), @(750,1334), @(1125,2436), @(1170,2532), @(1179,2556), @(1290,2796))) {
    New-SplashPng $splash[0] $splash[1]
  }

  # Modern browsers accept a PNG-compressed image inside an ICO container.
  $png = [System.IO.File]::ReadAllBytes((Join-Path $public "favicon-32.png"))
  $stream = [System.IO.File]::Create((Join-Path $public "favicon.ico"))
  $writer = [System.IO.BinaryWriter]::new($stream)
  try {
    $writer.Write([uint16]0); $writer.Write([uint16]1); $writer.Write([uint16]1)
    $writer.Write([byte]32); $writer.Write([byte]32); $writer.Write([byte]0); $writer.Write([byte]0)
    $writer.Write([uint16]1); $writer.Write([uint16]32); $writer.Write([uint32]$png.Length); $writer.Write([uint32]22)
    $writer.Write($png)
  } finally {
    $writer.Dispose()
  }
} finally {
  $source.Dispose()
}
